config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "bikes#index"
  get "/my-bikes", to: "bikes#mybikes"
  get "/my-bookings", to: "bookings#mybookings"
  get "/booking-confirmation/:id", to: "bookings#confirmation", as: "confirmation"


  resources :bikes, except: [:index] do
    resources :bookings, only: %i[create new] do
      member do
        post "approve", to: "bookings#approve", as: "approve"
      end
    end
  end
  resources :bookings, only: %i[destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bike.rb
class Bike < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_title_and_address,
    against: [ :title, :address ],
    using: {
      tsearch: { prefix: true }
    }

  has_many_attached :photos
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings
  validates :address, :price, :title, :photos, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :bike
  belongs_to :user
  validates :start_time, :end_time, :message, presence: true

  def total_sum
    price_per_day = self.bike.price
    days_booked = (self.end_time - self.start_time).to_i
    total_sum = price_per_day * days_booked
    return total_sum
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :bikes
  validates :first_name, :last_name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def my_booked_bikes
    bookings.map do |booking|
      booking.bike
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization
  before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

   # Pundit: allow-list approach
   after_action :verify_authorized, except: :index, unless: :skip_pundit?
   after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

   # Uncomment when you *really understand* Pundit!
   # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
   # def user_not_authorized
   #   flash[:alert] = "You are not authorized to perform this action."
   #   redirect_to(root_path)
   # end

   private

   def skip_pundit?
     devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
   end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  include PgSearch::Model

  before_action :set_bike, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: [:home, :index, :show]

  def index
    @bikes = policy_scope(Bike)

    if params[:search].present?
      @bikes = Bike.search_by_title_and_address(params[:search])
    else
      @bikes = policy_scope(Bike)
    end

    @markers = @bikes.geocoded.map do |bike|
      {
        lat: bike.latitude,
        lng: bike.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {bike: bike})
      }
    end
  end




  def mybikes
    @bikes = current_user.bikes
    authorize @bikes
  end

  def show
    authorize @bike
    @booking = Booking.new
  end

  def new
    @bike = Bike.new
    authorize @bike
  end

  def create
    @bike = Bike.new(bike_params)
    @bike.user = current_user
    authorize @bike

    if @bike.save
      redirect_to @bike, notice: "Bike listing was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @bike
  end

  def update
    authorize @bike
    if @bike.update(bike_params)
      redirect_to bike_path(@bike), notice: "Bike listing was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    # @bike = Bike.find(params[:id])
    authorize @bike
    @bike.destroy
    redirect_to root_path, notice: "Bike was successfully destroyed.",  status: :see_other
  end

  private

  def set_bike
    @bike = Bike.find(params[:id])
  end

  def bike_params
    params.require(:bike).permit(:title, :address, :price, photos: [])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @bike = Bike.find(params[:bike_id])
    @booking = Booking.new
    authorize @booking
  end

  def approve
    @booking = Booking.find(params[:id])
    # @bike = Bike.find(params[:bike_id])
    @booking.update(state: true)
    flash[:success] = "Booking successfully approved"
    authorize @booking
    redirect_to booking_path(@booking)
  end

  def create
    @bike = Bike.find(params[:bike_id])
    @booking = Booking.new(booking_params)
    @booking.bike = @bike
    @booking.user = current_user
    authorize @booking

    if current_user == @bike.user
      redirect_to @bike, alert: "You cannot book your own bike."
    elsif @booking.save
      redirect_to confirmation_path(@booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy
    redirect_to bike_path(@booking.bike), status: :see_other
  end

  def mybookings
    @bookings = Booking.joins(:bike).where(bikes: { user_id: current_user.id })
    @bikes = current_user.my_booked_bikes.uniq
    authorize @bookings
  end

  def confirmation
    @booking = Booking.find(params[:id])
    @bike = @booking.bike
    authorize @booking

    if params[:confirm_booking]
      if @booking.save
        redirect_to my_bookings_path, notice: 'You have Approved this bike.'
      else
        render :new
      end

    end
  end

  private

  def booking_params
    params.require(:booking).permit(:message, :start_time, :end_time)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikes/_info_window.html.erb
<h4><%= link_to bike.title, bike_path(bike), class: "text-decoration-none text-reset" %></h4>
<p><i class="fa-solid fa-location-dot"></i> <strong><%= bike.address %></strong></p>
<p>Price: £<%= bike.price %></p>

app/views/bikes/edit.html.erb
  <div class="m-4">
    <%= link_to root_path do %>
      <h2 class="p-1"><i class="fa-solid fa-left-long" id="plus"></i></h2>
    <% end %>
  </div>
<div class="container mt-3 bg-white p-4 round shadow" style="width: 50rem;">
  <h2 class="mb-3">Update Bike</h2>
    <%= simple_form_for @bike do |f| %>
    <%= f.input :address %>
    <%= f.input :price %>
    <%= f.input :availability %>
    <%= f.input :title %>
    <%# <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.button :submit, class: 'btn btn-primary' %>
    <% end %>
</div>

app/views/bikes/index.html.erb
  <%= render 'shared/banner' %>

  <div class="container mt-2">
    <div class="mt-3">
      <%# <%= link_to "Add a bike", new_bike_path, class: "btn btn-primary" if policy(Bike).new? %>
        <%= form_tag root_path, method: :get do %>
         <%= text_field_tag :search, params[:search], placeholder: "Search by title or address" %>
        <%= submit_tag "Search" %>
      <% end %>
      <% if policy(Bike).new? %>
        <%= link_to new_bike_path do %>
          <div class="d-flex p-2">
            <h2 class="p-1"><i class="fa-solid fa-plus" id="plus"></i></h2>
            <i class="fa-solid fa-bicycle"></i>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="row">
      <div class="col-8">
        <div class="cards-grid-2 mt-1">
          <% @bikes.each do |bike| %>
          <div class="card p-2 m-3 shadow round">
            <%= cl_image_tag bike.photos.first.key, height: 250, crop: :fill %>
            <div class="m-2">
              <h5 class="mb-3"><%= bike.title %></h5>
              <p><i class="fa-solid fa-location-dot"></i>  Address: <%= bike.address %></p>
              <h5 class="mb-4"><em> £<%= bike.price %></em></h5>
              <%= link_to 'View', bike_path(bike), class: "btn btn-primary" %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
      <div class="col-4">
        <div id="maplayout"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
  </div>

app/views/bikes/mybikes.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://static.giant-bicycles.com/Images/PageBuilder/PageElements/Banner_E-BikeProducts_MMT_WebsiteDesign_Brand_1595881505.jpg);">
  <div class="container">
    <h1>My bikes</h1>
    <p>Get moving with Bikeshare: Affordable and convenient bike rentals for every traveler!</p>
    <% if user_signed_in? %>
      <div class="btn-wrapper d-none">
      <a class="btn btn-flat" href="<%= new_user_session_path %>">Login</a>
      <span class="btn-subtext">No account? Sign up!</span>
    <% else %>
      <div class="btn-wrapper">
      <a class="btn btn-flat" href="<%= new_user_session_path %>">Login</a>
      <span class="btn-subtext">No account? Sign up!</span>
    <% end %>
    </div>
  </div>
</div>
<div class="container mt-4">
  <h4 class="mt-3">My Bikes</h4>
  <% if @bikes.empty? %>
  <p>You don't have any Bikes on BikeShare, You can Get Started <%= link_to new_bike_path do %><h2 id="link"><i class="fa-solid fa-plus"></i></h2></p>
  <% end %>
  <% else %>
  <%= link_to root_path do %>
    <h2 class="p-1"><i class="fa-solid fa-left-long" id="plus"></i></h2>
  <% end %>
  <div class="cards-grid mt-2
  ">
    <% @bikes.each do |bike| %>
      <div class="card p-3 m-3 shadow round" style="width: 27rem;">
        <%= cl_image_tag bike.photos.first.key, height: 250, crop: :fill %>
          <div class="m-2">
          <h5 class="mb-3"><%= bike.title %></h5>
          <h6 class="mb-3"><i class="fa-solid fa-location-dot"></i>  Address: <%= bike.address %></h6>
          <h5 class="mb-4"><em> £<%= bike.price %></em></h5>
          <%= button_to "Delete", bike_path(bike), class: "btn btn-primary mb-3", method: :delete %>
          <%= link_to "Edit", edit_bike_path(bike), class: "btn btn-primary"  %>
        </div>
      </div>
      </div>
  <% end %>
    <% end %>
  </div>
</div>

app/views/bikes/new.html.erb
<div class="m-4">
  <%= link_to root_path do %>
    <h2 class="p-1"><i class="fa-solid fa-left-long" id="plus"></i></h2>
  <% end %>
</div>
<div class="container mt-3 bg-white p-4 round shadow" style="width: 40rem;">
  <h2 class="mb-3">Create a new bike</h2>
  <%= simple_form_for [@bike] do |f| %>
    <%= f.input :address, class: "geocoder",
      input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
      wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}} %>
    <%= f.input :price %>
    <%# <%= f.input :availability%>
    <%= f.input :title %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.button :submit, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/bikes/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://thulestore.co.za/media/wysiwyg/categories/bike-trailers-front-child-bike-seats/desktop/banner-1.png);">
  <div class="container">
    <h1>View bike details</h1>
    <p>Get moving with Bikeshare: Affordable and convenient bike rentals for every traveler!</p>
    <% if user_signed_in? %>
      <div class="btn-wrapper d-none">
      <a class="btn btn-flat" href="<%= new_user_session_path %>">Login</a>
      <span class="btn-subtext">No account? Sign up!</span>
    <% else %>
      <div class="btn-wrapper">
      <a class="btn btn-flat" href="<%= new_user_session_path %>">Login</a>
      <span class="btn-subtext">No account? Sign up!</span>
    <% end %>
    </div>
  </div>
</div>
<div class="bg-white m-3">
  <div class="container p-3 ">
    <div class="row">
      <div class="col-md-6">
      <% if user_signed_in? %>
        <% if current_user == @bike.user%>
            <h3>Hi <%= current_user.first_name %>, Welcome</h3>
        <% else %>
            <h3>Hi <%= current_user.first_name %>, you have selected <%= @bike.title  %></h3>
        <p>Please add your dates and confirm all details to proceed with your booking</p>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>



<div class="container w-100">
  <div class="row">
    <div class="col-8 d-flex justify-content-center">
      <div class="card shadow m-2 shadow round p-2" style="width: 23rem;">
          <img class="card-img-top" src="<%= cl_image_path @bike.photos.first.key, height: 250, crop: :fill %>" alt="Card image cap">
          <div class="card-body">
          <h5 class="card-title"><%= @bike.title %></h5>
          <p class="card-text">
            <p class="mb-3"><i class="fa-solid fa-location-dot"></i> Address: <%= @bike.address%></p>
            <% if @bike.availability%>
                <p>Available</p>
            <% else %>
              <p>Available</p>
            <% end %>

            <% if current_user %>
              <% if policy(@bike).destroy? %>
                <%= button_to "Delete", bike_path(@bike), class: "btn btn-primary mb-3", method: :delete %>
              <% end %>
              <% if policy(@bike).edit? %>
                <%= link_to "Edit", edit_bike_path(@bike), class: "btn btn-primary"  %>
              <% end %>
            <% end %>
          </div>
      </div>
    </div>
    <div class="col-4">
  <% unless current_user == @bike.user %>
    <h5>Book this Bike</h5>
    <div class="col-m-4 round shadow">
      <div class="bg-white border p-3 sticky-top round shadow">
        <% if user_signed_in? %>
          <p><%= link_to 'Book', new_bike_booking_path(@bike), class: "btn btn-primary w-100" %></p>
        <% else %>
          <p><%= link_to 'Sign-Up', new_user_registration_path, class: "btn btn-primary w-100" %></p>
        <% end %>
        <div class="d-flex justify-content-between mt-3">
          <p><%= @bike.title %></p>
          <p>£<%= @bike.price %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="mr-4">
  <%= link_to root_path do %>
    <h2 class="p-4"><i class="fa-solid fa-left-long" id="plus"></i></h2>
  <% end %>
</div>

app/views/bookings/confirmation.html.erb
<div class="container mt-3 bg-white p-4 round shadow" style="width: 30rem;">
  <h2 class="mb-3">Booking Confirmed!</h2>
  <p class="mb-5">These Are Your Booking Details:</p>
    <h4 class="mb-4"><%= @booking.bike.title %></h4>
    <h6>Start Date: <%= @booking.start_time.strftime("%b %d, %Y") %></h6>
    <h6 class="mb-4">End Date: <%= @booking.end_time.strftime("%b %d, %Y") %></h6>
    <h5 class="mb-4"><strong><%= number_to_currency(@booking.total_sum, unit: "£") %></strong></h5>
    <%= link_to "Make Payment", my_bookings_path, class: "btn btn-primary" %>
</div>

app/views/bookings/mybookings.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://static.giant-bicycles.com/Images/PageBuilder/PageElements/Banner_E-BikeProducts_MMT_WebsiteDesign_Brand_1595881505.jpg);">
  <div class="container">
    <h1>Bookings</h1>
    <p>Get moving with Bikeshare: Affordable and convenient bike rentals for every traveler!</p>
    <% if user_signed_in? %>
      <div class="btn-wrapper d-none">
      <a class="btn btn-flat" href="<%= new_user_session_path %>">Login</a>
      <span class="btn-subtext">No account? Sign up!</span>
    <% else %>
      <div class="btn-wrapper">
      <a class="btn btn-flat" href="<%= new_user_session_path %>">Login</a>
      <span class="btn-subtext">No account? Sign up!</span>
    <% end %>
    </div>
  </div>
</div>

<div class="container mt-4">
  <h3>My Booked Bikes:</h3>
    <% if @bookings.empty? %>
    <p>You have not received any Booking for your Bikes yet.</p>
    <% else %>
    <div class="cards-grid mt-5">
    <% @bookings.each do |booking| %>
    <div class="card p-3 shadow round">
      <%= cl_image_tag booking.bike.photos.first.key, height: 250, crop: :fill %>
        <div class="m-2">
          <h5 class="mb-3"><%= booking.bike.title %></h5>
          <p><strong>Start: <%= booking.start_time.strftime("%b %d, %Y") %></strong></p>
          <p class="mb-3"><strong>End: <%= booking.end_time.strftime("%b %d, %Y") %></strong></p>
          <p><i class="fa-solid fa-location-dot"></i>  Address: <%= booking.bike.address %></p>
          <p><em>"<%= booking.message %>"</em></p>
          <% if booking.state? %>
            <%= button_to 'Approved', approve_bike_booking_path(booking.bike, booking), method: :post, class: "btn btn-success" %>
            <% else %>
             <%= button_to 'Approve', approve_bike_booking_path(booking.bike, booking), method: :post, class: "btn btn-success" %>
          <% end %>
        </div>
    </div>
    <% end %>
  </div>
    <% end %>
</div>

<div class="container my-4">
  <h3>Bikes That I Booked: </h3>
  <% if @bikes.empty? %>
  <p>You have not Booked Any Bike yet. Make your first Booking? <%= link_to "Explore", root_path, class: "btn btn-primary" %></p>
  <% else %>
  <div class="cards-grid mt-5">
      <% @bikes.each do |bike|  %>
    <div class="card p-3 shadow round">
      <%= cl_image_tag bike.photos.first.key, height: 250, crop: :fill %>
      <div class="m-2">
        <h5 class="mb-3"><%= bike.title %></h5>
        <p><i class="fa-solid fa-location-dot"></i> <strong>Pick-Up Point: </p>
        <p class="mb-6"></strong><%= bike.address %></p>
        <% bike.bookings.each do |booking| %>
        <% if booking.state %>
          <p class="mt-3"><em>Booking accepted.</em></p>
          <%= button_to booking_path(booking), method: :delete do %>
          <h2 id="cancel"><i class="fa-sharp fa-solid fa-xmark"></i></h2><% end %>
        <% else %>
          <p><em>Pending Approval. Please Wait</em></p>
          <% end %>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
  <% end %>

</div>
<div class="mr-4">
  <%= link_to root_path do %>
    <h2 class="p-4"><i class="fa-solid fa-left-long" id="plus"></i></h2>
  <% end %>
</div>

app/views/bookings/new.html.erb
<div class="container mt-3 bg-white p-4 round shadow" style="width: 40rem;">

  <h4 class="mb-3">Book A Bike</h4>
  <%= simple_form_for [@bike, @booking], data: { controller: 'flatpickr' } do |f| %>
    <%= f.input :start_time, as: :string, input_html: { data: { flatpickr_target: "startTime" } } %>
     <%= f.input :end_time, as: :string, input_html: { data: { flatpickr_target: "endTime" }, id: 'end_time' } %>
    <%= f.input :message %>
    <%= f.button :submit, class: 'btn btn-primary' %>
  <% end %>
  <%= link_to "Back to Bikes", root_path, class: "btn btn-secondary mt-5" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bikeshare</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>

  </head>

  <body>
      <%= render "shared/navbar" %>
      <%= render "shared/flashes" %>
    <%= yield %>
    <%= render partial: 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://mikesbiketoursamsterdam.com/wp-content/uploads/2021/05/A-bike-1.jpeg);">
  <div class="container">
    <h1><span data-controller="typed-js"></span></h1>
    <p>Get moving with Bikeshare: Affordable and convenient bike rentals for every traveler!</p>
    <% if user_signed_in? %>
      <div class="btn-wrapper d-none">
      <a class="btn btn-flat" href="<%= new_user_session_path %>">Login</a>
      <span class="btn-subtext">No account? Sign up!</span>
    <% else %>
      <div class="btn-wrapper">
      <a class="btn btn-flat" href="<%= new_user_session_path %>">Login</a>
      <span class="btn-subtext">No account? Sign up!</span>
    <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <p>© 2023 PaidFast Team</p>
  <ul>
    <li>
      <a href="https://github.com/Kolawoleakinmosin">
        <img src="https://avatars.githubusercontent.com/Kolawoleakinmosin?s=25" alt="Kolawoleakinmosin GitHub Profile" />
        Samuel
      </a>
    </li>
    <li>
      <a href="https://github.com/dereuckkarmen">
        <img src="https://avatars.githubusercontent.com/dereuckkarmen?s=25" alt="Dereuckkarmen GitHub Profile" />
        Karmen
      </a>
    </li>
    <li>
      <a href="https://github.com/polotime">
        <img src="https://avatars.githubusercontent.com/polotime?s=25" alt="Polotime GitHub Profile" />
        Paul
      </a>
    </li>
    <li>
      <a href="https://github.com/costaleandrop">
        <img src="https://avatars.githubusercontent.com/costaleandrop?s=25" alt="Costaleandrop GitHub Profile" />
        Leandro
      </a>
    </li>
  </ul>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to image_tag("bike-logo.jpg", alt: "bike logo"), root_path, class: "navbar-brand" %>



    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to current_user.first_name, "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Bikes", my_bikes_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Bookings", my_bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>